package com.clockbone.model;

import java.util.Date;

public class Order {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.id
     *
     * @mbggenerated Wed Mar 16 11:12:37 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.createtime
     *
     * @mbggenerated Wed Mar 16 11:12:37 CST 2016
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.username
     *
     * @mbggenerated Wed Mar 16 11:12:37 CST 2016
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.order_id
     *
     * @mbggenerated Wed Mar 16 11:12:37 CST 2016
     */
    private String orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.order_type
     *
     * @mbggenerated Wed Mar 16 11:12:37 CST 2016
     */
    private String orderType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.updatetime
     *
     * @mbggenerated Wed Mar 16 11:12:37 CST 2016
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.order_status
     *
     * @mbggenerated Wed Mar 16 11:12:37 CST 2016
     */
    private String orderStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.ip
     *
     * @mbggenerated Wed Mar 16 11:12:37 CST 2016
     */
    private String ip;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.id
     *
     * @return the value of t_order.id
     *
     * @mbggenerated Wed Mar 16 11:12:37 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.id
     *
     * @param id the value for t_order.id
     *
     * @mbggenerated Wed Mar 16 11:12:37 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.createtime
     *
     * @return the value of t_order.createtime
     *
     * @mbggenerated Wed Mar 16 11:12:37 CST 2016
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.createtime
     *
     * @param createtime the value for t_order.createtime
     *
     * @mbggenerated Wed Mar 16 11:12:37 CST 2016
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.username
     *
     * @return the value of t_order.username
     *
     * @mbggenerated Wed Mar 16 11:12:37 CST 2016
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.username
     *
     * @param userName the value for t_order.username
     *
     * @mbggenerated Wed Mar 16 11:12:37 CST 2016
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.order_id
     *
     * @return the value of t_order.order_id
     *
     * @mbggenerated Wed Mar 16 11:12:37 CST 2016
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.order_id
     *
     * @param orderId the value for t_order.order_id
     *
     * @mbggenerated Wed Mar 16 11:12:37 CST 2016
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.order_type
     *
     * @return the value of t_order.order_type
     *
     * @mbggenerated Wed Mar 16 11:12:37 CST 2016
     */
    public String getOrderType() {
        return orderType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.order_type
     *
     * @param orderType the value for t_order.order_type
     *
     * @mbggenerated Wed Mar 16 11:12:37 CST 2016
     */
    public void setOrderType(String orderType) {
        this.orderType = orderType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.updatetime
     *
     * @return the value of t_order.updatetime
     *
     * @mbggenerated Wed Mar 16 11:12:37 CST 2016
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.updatetime
     *
     * @param updateTime the value for t_order.updatetime
     *
     * @mbggenerated Wed Mar 16 11:12:37 CST 2016
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.order_status
     *
     * @return the value of t_order.order_status
     *
     * @mbggenerated Wed Mar 16 11:12:37 CST 2016
     */
    public String getOrderStatus() {
        return orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.order_status
     *
     * @param orderStatus the value for t_order.order_status
     *
     * @mbggenerated Wed Mar 16 11:12:37 CST 2016
     */
    public void setOrderStatus(String orderStatus) {
        this.orderStatus = orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.ip
     *
     * @return the value of t_order.ip
     *
     * @mbggenerated Wed Mar 16 11:12:37 CST 2016
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.ip
     *
     * @param ip the value for t_order.ip
     *
     * @mbggenerated Wed Mar 16 11:12:37 CST 2016
     */
    public void setIp(String ip) {
        this.ip = ip;
    }


    @Override
    public String toString() {
        return "Order{" +
                "id=" + id +
                ", createtime=" + createtime +
                ", userName='" + userName + '\'' +
                ", orderId='" + orderId + '\'' +
                ", orderType='" + orderType + '\'' +
                ", updateTime=" + updateTime +
                ", orderStatus='" + orderStatus + '\'' +
                ", ip='" + ip + '\'' +
                '}';
    }
}